### PR TITLE
Add result categories

### PR DESCRIPTION
**Pull request by koertho**
This is a follow up for #16 and add categories to multiple choice questions as discussed in #15 .

There was some refactoring needed as the datastructure for group widget is different then textWizard. I hope I found all occurences.

### CODE REVIEW

**Comment by cmette** [comment]
@koertho mdevster asked me for a review of contao-survey and I took a look at the branch here. First of all, thank you very much for your extensive involvement. I could not find any problems at the moment. For me the bundle works fine with the new features. 

i would have only one insignificant comment. 
1. when i create a brand new multiple choice question. 
2. and if after that I go to the palette "Question specific settings". -> "Answers" I want to add a new question
3. and if I use a high resolution screen.

Then 
-> the green button looks a bit out of place at first (see screenshot). I did not notice it at all in this location. 

screenshot-contao409 local-2022 09 01-09_34_49

maybe this can be designed differently?

**Comment by koertho** [comment]
I will try to adjust the styling, but it comes from the group widget where the button is placed in the center by default.

This PR is still work in progress, I will add another commit later, I would prefer review and merge #16 first.

**Comment by koertho** [comment]
I think we can ship this feature :)

**Review by cmette — APPROVED** [review]
I did not immediately find all the changes to the BE. For a comprehensive test, a comparison survey would be beneficial. 
I have not found any errors. It looks like scales and categories are working. On the BE they look like this:
survey-2022 10 04-08_55_34
On the FE they look like this. 

survey-2022 10 04-08_57_48


I would have expected something different there. For my sake a select field or similar.

Otherwise I haven't noticed any problems. Thanks for your efforts!

**Comment by koertho** [comment]
Oh, there are missing translations! Please do not merge, I'll fix it before!

Categories are not shown in the frontend (if you do not output them), or what do you mean with "I would have expected something different there."?

**Comment by koertho** [comment]
@cmette Did you use the latest commits for your review? For me, all translations are loaded :/

Changes in the backend are: 
- Survey settings have an option "Add categories" and a definition group widget for this
- Multiple choice question type has now a group widget for answers. If categories activated, it shows a second column for categories.
- The result statistics now also show categories.

**Comment by koertho** [comment]
Since I could not reproduce the translation issue, I would have no objections in merging it :)

**Comment by koertho** [comment]
@cmette I found the issue you mean with your Backend/Frontend comment and fixed it

**Comment by cmette** [comment]
Thank you very much for your comments. Please excuse my late reply. I will test the current status today.

**Comment by koertho** [comment]
No problem. I know how short time is ;)

**Comment by cmette** [comment]
moin moin - ok i have now checked the following

1. "missing translations": I didn't notice that at all, but now I've tested it. If you switch the user language to english, the translations in the file en\tl_survey_question.php are missing. The english translation is very different from the de/tl_survey_question.php! Therefore the translations are really missing.
2. "Categories are not shown in the frontend ... what do you mean with ...?" Since the survey bundle can be configured extensively and I don't have a test survey available, I unfortunately can't fully test the desired behavior. It would be advantageous if I had a reference survey on which I can test the desired behavior.
3. https://github.com/pdir/contao-survey/pull/17#issuecomment-1273075409 : may be that the translations are all loaded, but the en/tl_survey_question.php does not have the expected [content](https://github.com/heimrichhannot/contao-survey/blob/8b801d331c91e50bc35345d10c42e39f75e6cb08/src/Resources/contao/languages/de/tl_survey_question.php#L37). I have not yet looked at the other two innovations mentioned.
4. "the green button": is no problem :blush: 

I will try to contact you via Slack, maybe that will be faster...

**Comment by koertho** [comment]
I've added the missing english translations for the choices field

**Review by MDevster — APPROVED** [review]

**Comment by MDevster** [comment]
Thank you @koertho

**Pull request merged**
