### PR TITLE
Add result page type

### PR DESCRIPTION
**Pull request by koertho**
This PR add a new page type to display results within the survey.

> ~~This PR is not ready for merge, just my current work state. I would like to receive Feedback if you like my approach or if I need to change some things.~~

This PR add a new type field to the survey pages. The new type "result" will use a different template than the default (question) page type. Result page can not have questions added. Instead, the template get the survey result data and the answers of the current user. I'll added two default templates, one for the complete and one for the user specific data. 

Changes:
- I raised contao and php version dependencies
- I added icons for the page types (I used icons from bootstrap icons, but that can be altered)
- I added an editHeader operation to survey page dca
- As I needed to touch the template handling I added a filter to the survey page template list to skip template for questions and question results

Open work: 
- [x] Styling for result pages (themes)
- [x] Translations for new database fields
- [x] Title for page icon
- [x] Show correct questions text in result page

### CODE REVIEW

**Comment by koertho** [comment]
Ok, I couldn't find any usage of the themes folder and when adding them manually, only some elements are styled, so I think the current output of my result page is ok as it is.

**Comment by koertho** [comment]
I just added some enhancements :)

**Comment by MDevster** [comment]
@koertho You are ready so far and we can check it and merge if necessary?

**Comment by koertho** [comment]
Yes, I'm done so far.

**Comment by koertho** [comment]
I added a small fix: I removed two property types and raised the minimum PHP version to 7.2, as contao 4.9 requires at least 7.2.

**Comment by koertho** [comment]
Fixed another issue I found while working on the categories. The edit button on survey page was not disabled if survey has data.

**Comment by cmette** [comment]
the ecs error can be fixed by removing the php comment characters /* in the ecs.php (in the bundle root). The ecs now sets these automatically in the ecsHeader.

The call should work like before:
```.\vendor\bin\ecs check src --fix```

In newer bundles the call can also be made via 
```composer run-script cs-fixer```
as long as the ecs is declared as a script in composer.json.

**Comment by koertho** [comment]
@cmette Thanks! I've got it working. I added the fixed config file to the PR.
I just run the script on the new classes outside the resource folder as there are to many issues in the old code.

**Comment by koertho** [comment]
We're currently using my changes in a customer project, so we found and fixes some issues. We also added two small enhancements to the result page type: custom next-button text for the former page (so you can display e.g. "show results" instead of "next") and hide the back button for the current page. I hope we need no more changes :)

**Pull request merged**
