### PR TITLE
Fixed for issues with php 8 and multiple choices

### PR DESCRIPTION
**Pull request by koertho**
This PR fixes a lot of php 8 array index warning and a bug in backend for multiple choice questions.

Changelog:
- Changed: refactored logic to disable tl_survey.access field to DataContainer class
- Changed: refactored logic to close tl_survey_page to DataContainer class
- Fixed: wrong comparison in CategoriesListener
- Fixed: buggy code in SurveyQuestionMultiplechoice leading to different return values
- Fixed: dublicated code in SurveyResultDetails
- Fixed: a lot of php 8 related array index issues (see #27)
- Fixed: tl_survey_page operations not correctly disabled

### CODE REVIEW

**Comment by koertho** [comment]
I've fixed two additional bugs for survey page. And I've run ecs fixer on my touched file except the legacy classes (there were to many changes).

**Comment by koertho** [comment]
And another one (hopefully the last one for now): I've fixed a syntax issue and array index issues when using survey with cookies.

**Review by cmette — APPROVED** [review]

**Review by MDevster — APPROVED** [review]

**Comment by koertho** [comment]
Should I resolve the conflicts or will you do it?

**Comment by cmette** [comment]
> Should I resolve the conflicts or will you do it?
have you seen my Slack message?

**Pull request merged**
